/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.OpcionesControlador;
import Controlador.SalirControlador;

/**
 *
 * @author Snack
 */
public class VOpciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */
    public VOpciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jIconLeeyAprende = new javax.swing.JLabel();
        JModificarLibros = new javax.swing.JPanel();
        JLibrosOpen = new javax.swing.JLabel();
        JModificarUsuarios = new javax.swing.JPanel();
        JSociosOpen = new javax.swing.JLabel();
        JVerContabilidad = new javax.swing.JPanel();
        JPrestamosOpen = new javax.swing.JLabel();
        JModificarBiblioteca = new javax.swing.JPanel();
        JBibliotecaOpen = new javax.swing.JLabel();
        jLibros = new javax.swing.JLabel();
        jLibros1 = new javax.swing.JLabel();
        jPrestamos = new javax.swing.JLabel();
        jBiblioteca = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMenuCerrarSesion = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jIconLeeyAprende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/LibraryIcon.png"))); // NOI18N

        JLibrosOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1467285836_OFFice-33.png"))); // NOI18N
        JLibrosOpen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLibrosOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLibrosOpenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JModificarLibrosLayout = new javax.swing.GroupLayout(JModificarLibros);
        JModificarLibros.setLayout(JModificarLibrosLayout);
        JModificarLibrosLayout.setHorizontalGroup(
            JModificarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLibrosOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JModificarLibrosLayout.setVerticalGroup(
            JModificarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLibrosOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JSociosOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1467284734_OFFice-66.png"))); // NOI18N
        JSociosOpen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JSociosOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JSociosOpenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JModificarUsuariosLayout = new javax.swing.GroupLayout(JModificarUsuarios);
        JModificarUsuarios.setLayout(JModificarUsuariosLayout);
        JModificarUsuariosLayout.setHorizontalGroup(
            JModificarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSociosOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JModificarUsuariosLayout.setVerticalGroup(
            JModificarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JSociosOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPrestamosOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1467284813_OFFice-90.png"))); // NOI18N
        JPrestamosOpen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JPrestamosOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPrestamosOpenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JVerContabilidadLayout = new javax.swing.GroupLayout(JVerContabilidad);
        JVerContabilidad.setLayout(JVerContabilidadLayout);
        JVerContabilidadLayout.setHorizontalGroup(
            JVerContabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPrestamosOpen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JVerContabilidadLayout.setVerticalGroup(
            JVerContabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPrestamosOpen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JBibliotecaOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1467286183_bookshelf.png"))); // NOI18N
        JBibliotecaOpen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBibliotecaOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBibliotecaOpenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JModificarBibliotecaLayout = new javax.swing.GroupLayout(JModificarBiblioteca);
        JModificarBiblioteca.setLayout(JModificarBibliotecaLayout);
        JModificarBibliotecaLayout.setHorizontalGroup(
            JModificarBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JBibliotecaOpen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JModificarBibliotecaLayout.setVerticalGroup(
            JModificarBibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JBibliotecaOpen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLibros.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLibros.setText("Libros");

        jLibros1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLibros1.setText("Socios");

        jPrestamos.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jPrestamos.setText("Préstamos");

        jBiblioteca.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jBiblioteca.setText("Biblioteca");

        jMenu1.setText("Opciones");

        JMenuCerrarSesion.setText("Cerrar Sesión");
        JMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(JMenuCerrarSesion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLibros)
                .addGap(176, 176, 176)
                .addComponent(jLibros1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPrestamos)
                .addGap(149, 149, 149))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JModificarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(JModificarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JModificarBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addComponent(JVerContabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jBiblioteca))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jIconLeeyAprende)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jIconLeeyAprende)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JModificarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JModificarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JVerContabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLibros)
                    .addComponent(jLibros1)
                    .addComponent(jPrestamos))
                .addGap(48, 48, 48)
                .addComponent(JModificarBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBiblioteca)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JLibrosOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLibrosOpenMouseClicked
        OpcionesControlador OpcionesControlador = new OpcionesControlador();
        OpcionesControlador.actionPerformedJLibrosOpen(evt);
        this.setVisible(false);
    }//GEN-LAST:event_JLibrosOpenMouseClicked

    private void JSociosOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JSociosOpenMouseClicked
        OpcionesControlador OpcionesControlador = new OpcionesControlador();
        OpcionesControlador.actionPerformedJSociosOpen(evt);
        this.setVisible(false);
    }//GEN-LAST:event_JSociosOpenMouseClicked

    private void JPrestamosOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPrestamosOpenMouseClicked
        OpcionesControlador OpcionesControlador = new OpcionesControlador();
        OpcionesControlador.actionPerformedJPrestamosOpen(evt);
        this.setVisible(false);
    }//GEN-LAST:event_JPrestamosOpenMouseClicked

    private void JBibliotecaOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBibliotecaOpenMouseClicked
        OpcionesControlador OpcionesControlador = new OpcionesControlador();
        OpcionesControlador.actionPerformedJBibliotecaOpen(evt);
        this.setVisible(false);
    }//GEN-LAST:event_JBibliotecaOpenMouseClicked

    private void JMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuCerrarSesionActionPerformed
        SalirControlador SalirControlador = new SalirControlador();
        SalirControlador.actionPerformed(evt);
        this.setVisible(false);
    }//GEN-LAST:event_JMenuCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VOpciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOpciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JBibliotecaOpen;
    public javax.swing.JLabel JLibrosOpen;
    private javax.swing.JMenuItem JMenuCerrarSesion;
    private javax.swing.JPanel JModificarBiblioteca;
    private javax.swing.JPanel JModificarLibros;
    private javax.swing.JPanel JModificarUsuarios;
    public javax.swing.JLabel JPrestamosOpen;
    public javax.swing.JLabel JSociosOpen;
    private javax.swing.JPanel JVerContabilidad;
    private javax.swing.JLabel jBiblioteca;
    private javax.swing.JLabel jIconLeeyAprende;
    private javax.swing.JLabel jLibros;
    private javax.swing.JLabel jLibros1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel jPrestamos;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
